### PR TITLE
Add getter for HTML and Text message body

### PR DESCRIPTION
**Pull request by qutaiba**
I ve just added two getter for message html body and text body as a lot of businesses require saving emails after sending them

### CODE REVIEW

**Comment by bryglen** [comment]
This can be done through Yii::$app->sendGrid->getText() isn't it?

**Comment by qutaiba** [comment]
No man it doesn't work this way even if you try to use Yii::$app->sendGrid->getHtml() it will generate an error saying that this function is not defined can you please add the fucntions to your repo so I can use it it caused an error today when it was updated on production.

**Comment by bryglen** [comment]
Actually.. try this

Yii::$app->sendGrid->getSendGridMailer()->getText()

**Comment by qutaiba** [comment]
unfortunately it is the same 
Call to undefined method SendGrid::getText()

**Comment by qutaiba** [comment]
and it make more scene to pull the message html or text from the composed message not from sendGrid instance.

**Comment by bryglen** [comment]
well. it doesn't make sense as well.

`Yii::$app->sendGrid->getSendGridMailer()->getText()`

is same with

``` php
public function getTextBody()
{
    return $this->getSendGridMessage()->getText();
}
```

**Comment by bryglen** [comment]
Show your code I can help at least.. but it doesn't really make sense to include it on the extension which you can access the SendGrid methods

**Comment by bryglen** [comment]
Actually my mistake. I put wrong code. try this

``` php
$sendGrid = Yii::$app->sendGrid;
$message = $sendGrid->compose('contact/html', ['contactForm' => $form]);
$message->getSendGridMessage()->getText();
```

**Comment by qutaiba** [comment]
Great body, works this way thanks.

**Pull request closed without merging**
